spring:
  application:
    name: registry
server:
  port: ${PORT:8080}

eureka:
  instance:
    hostname: secret-anchorage-03030.herokuapp.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/
      non-secure-port: 80
      secure-port: 443
